# testthat snapshots are machine-generated regression tests that
# have to be preserved exactly as they are
exclude: '^tests/testthat/_snaps/.*$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: mixed-line-ending

-   repo: https://github.com/lorenzwalthert/precommit
    rev: 1ad5174c51b14a25aded40032d29441d4265bb08  # frozen: v0.4.3.9017
    hooks:
    -   id: parsable-R
    -   id: deps-in-desc
        args: [--allow_private_imports]
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: readme-rmd-rendered
    -   id: use-tidy-description
ci:
    autoupdate_schedule: weekly
